[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'magicalbanana/vim-sql-syntax'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'yuratomo/w3m.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
on_ft = 'php'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = 'javascript'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 't9md/vim-choosewin'

[[plugins]]
repo = 'tanabe/ToggleCase-vim'

[[plugins]]
repo = 'tfnico/vim-gradle'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'vim-scripts/groovy.vim'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = 'php'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'noahfrederick/vim-composer'

[[plugins]]
repo = 'noahfrederick/vim-laravel'

[[plugins]]
repo = 'jwalton512/vim-blade'

[[plugins]]
repo = 'zah/nim.vim'

[[plugins]]
repo = 'mattn/vim-particle'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
